# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_negative_values',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='opperation_type',
            field=models.CharField(choices=[('add', 'Addition'), ('sub', 'Subtraction'), ('mul', 'Multiplication'), ('div', 'Division'), ('unk', 'Unknown')], default='unk', max_length=3),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.IntegerField(),
        ),
    ]
