# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('text', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[(b'add', 'Addition'), (b'sub', 'Subtraction'), (b'mul', 'Multiplication'), (b'div', 'Division'), (b'unk', 'Unknown')], default='unk', max_length=3)),
                ('text', models.CharField(max_length=300, unique=True)),
                ('has_negative_values', models.BooleanField(default=False)),
                ('correct_answer_id', models.IntegerField(unique=True)),
                ('answers', models.ManyToManyField(related_name='answers', to='api.Answer')),
            ],
        ),
    ]
