# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AddField(
            model_name='symptom',
            name='diagnosis',
            field=models.ManyToManyField(through='api.DiagnosisToSymptom', to='api.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosistosymptom',
            name='diagnosis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_id', to='api.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosistosymptom',
            name='symptom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_id', to='api.Symptom'),
        ),
    ]
