# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180320_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosistosymptom',
            old_name='diagnosis_id',
            new_name='diagnosis',
        ),
        migrations.RenameField(
            model_name='diagnosistosymptom',
            old_name='symptom_id',
            new_name='symptom',
        ),
    ]
